### ISSUE TITLE
Can you help me th hackintosh?

### ISSUE THREAD

**Issue by ghost** [m0d16l14n1/ideapad330-15arr-hackintosh#1]
I am a Chinese,and I am a boy. So I can't speak English.
我的电脑用了你的这个无法进去系统。这个怎么办

**Comment by m0d16l14n1** [comment]
what kind of problem you have? what`s your laptop?

**Comment by ghost** [comment]
我有一个clover的引导，我已经配置好了，我打算换成oc可是不会配置

**Comment by ghost** [comment]
[EFI.zip](https://github.com/m0d16l14n1/ideapad330-15arr-hackintosh/files/4839593/EFI.zip)
这个就是我配置好的

**Comment by m0d16l14n1** [comment]
don't use Clover, try with OpenCore
You can try with my EFI and if it work - you can check how to setup your own by comparing default OC config.plist and mine

**Comment by ghost** [comment]
我刚才用了一下你的这个，不过情况并不乐观，我卡在了一行代码
![0~Q$E0~_LY@Q@ URW$B~WG0](https://user-images.githubusercontent.com/65110036/85911693-20327800-b859-11ea-82f0-f1b98b6944f4.jpg)

**Comment by YoungYangYoung** [comment]
Hi,AMD Ryzen 7 4800U can work?
My laptop is Lenovo 13 PRO R7 4800U (2020).

**Comment by m0d16l14n1** [comment]
> Hi,AMD Ryzen 7 4800U can work?
> 
> My laptop is Lenovo 13 PRO R7 4800U (2020).

possible. just try it

**Comment by Razdo27** [comment]
[opencore-2020-09-11-094040.txt](https://github.com/m0d16l14n1/ideapad330-15arr-hackintosh/files/5205965/opencore-2020-09-11-094040.txt)

I tried this and got compatibility error. So I disable the checker and tried. But it gets stuck at the last line in the log I have uploaded. Please help me. I have also uploaded my config.plist file.
[config.zip](https://github.com/m0d16l14n1/ideapad330-15arr-hackintosh/files/5205975/config.zip)

**Comment by Razdo27** [comment]
also, my smbios is macbook1,1. should i replace it with what you have in your config.plist?

**Comment by Razdo27** [comment]
Update- 
I used the given config.plist and took a snapshot of my oc folder. Now it boots up. Thanks man! I really needed this!

**Comment by m0d16l14n1** [comment]
nice
