### ISSUE TITLE
Не продвигается дальше ребута.

### ISSUE THREAD

**Issue by oliyase** [m0d16l14n1/ideapad330-15arr-hackintosh#2]
Увидел что вы русский по скриншоту. Загружаюсь с флешки, все было хорошо, первый этап установки (копирование и ребут) прошел успешно, но потом зависает на логе. Везде в разных местах - USB, PS/2. В меню OpenCore выбирал "Install macOS". Модель: 330-15ARR 81D2 (ryzen 2200u)

**Comment by m0d16l14n1** [comment]
Я же писал, что там проблема с USB, поэтому оно и стопорится. Пробуй ребутится, пока не запустится нормально, либо подкидывай XHCI unsupported

**Comment by oliyase** [comment]
> Я же писал, что там проблема с USB, поэтому оно и стопорится. Пробуй ребутится, пока не запустится нормально, либо подкидывай XHCI unsupported

Закинул USB Injector от рехаба. Оно запустилось, но просит начать установку заново, что я сейчас и сделаю
